<<<<<<< HEAD

version: '2'
=======
version: "2"
>>>>>>> dockerbranch

services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
<<<<<<< HEAD
      - 8080:3000
=======
      - 3000:3000
>>>>>>> dockerbranch
    env_file:
      - .env
    links:
      - database
<<<<<<< HEAD
    command: ['npm', 'start']
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 11543:5432
    volumes:
      - database-data:/var/lib/postgresql/data
=======
    command: ["npm", "start"]
    depends_on:
      - database
  database:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USERNAME: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
>>>>>>> dockerbranch

volumes:
  database-data: {}