version: "2"

services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - database
    command: ["npm", "start"]
    depends_on:
      - database
  database:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USERNAME: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}

volumes:
  database-data: {}